### ISSUE TITLE
Feature request: ask how to handle the symlinks before adding them to the bare repo  

### ISSUE THREAD

**Issue by kguidonimartins** [kazhala/dotbare#11]
Once again, thanks for this fantastic tool (especially the `fedit` command that centralizes all files). I tried your strategy of migrating from a symbolic link system to dotbare. It didn't work out as I expected. After following your instructions, `fadd` added the file as a symbolic link, not as a real file. Perhaps, I did not understand your instructions as I should, or your strategy does not intend to solve this problem.

I don't know how to report this here, but I created a script based on your `fadd` function. It contains a symbolic link integrity check and asks the user how to handle the file before adding it to the bare repository created by dotbare.

Here's the script.

```bash
#!/usr/bin/env bash

function return_file() {
    local file=$1
    if [ -z "${file}" ]; then
        echo "Not a file."
        exit 1
    else
        if [ -L "${file}" ]; then
            if [ -e "${file}" ]; then
                while true; do
                    read -r -p " This file is a symbolic link. What do you want to do?
                    1 - Return it to its original path and add it to the dotbare (Y/N)
                    2 - Add it as a symbolic link (L)
                    Answer: " answer
                    case $answer in
                        [Yy]* ) mv "$(readlink "${file}")" "${file}"; break;;
                        [Nn]* ) echo "Exiting"; exit 1;;
                        [Ll]* ) echo "Adding your file as a symlink"; break;;
                        * ) echo "Please answer yes or no.";;
                    esac
                done
            else
                echo "This is a broken link."
                exit 1
            fi
        elif [ -e "${file}" ]; then
            echo "Not a link"
        else
            echo "Missing"
        fi
        /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" add ${file}
    fi
}

return_file "$1"
```

Unfortunately, this has to be done for each file. In my case, it's an opportunity to review the really important files.

Feel free to close this issue without an answer. I would just like to register my dirty solution here. Sorry for messing up your repository.

**Comment by kazhala** [comment]
Sorry I couldn't yet reproduce the issue for `dotbare fadd`. Could you give a bit more context of how you migrated (Did you do the complete [migration](https://github.com/kazhala/dotbare#complete-migration) or just the integration specified [here](https://github.com/kazhala/dotbare#keep-your-current-setup-but-integrate-dotbare))?

Below is a screenshot for very simple integration, the git repo is the `testing` directory and within it, there is the `.git`. I point DOTBARE_DIR to `$HOME/testing/.git` and DOTBARE_TREE to `$HOME/testing`, this way there's no symlink involved.
![Screen Shot 2020-06-11 at 09 09 56](https://user-images.githubusercontent.com/43941510/84327952-02f87b00-abc4-11ea-9876-422cadcd9c12.png)

Sorry, I'm sure I didn't quite understand with what you described yet, on the second read of the issue seems like you are doing the migration in place within your current system? But I don't know how `dotbare fadd` could recognize symlink and added them.

Regardless I'm glad you found `dotbare` useful and I really liked your solution, checking symlinks and moving the file back to the appropriate location.

**Comment by kguidonimartins** [comment]
Sorry if I wasn't clear enough. English is not my first language. 

In my current system, I have all my dotfiles stored in folder `$HOME/dotfiles` and symlinks all of them to the appropriate location. I was thinking that `dotbare` could revert my system, returning the symlinks to their original location (as in my function above), and adding them to a new bare repo (as defined in `$DOTBARE_DIR`). It would be as if I had given up on my current approach and `dotbare` would solve all the problems. :facepalm:

I'm sure I didn't understand your instructions. My fault. I think I was trying a mixed approach between the [integration](https://github.com/kazhala/dotbare#keep-your-current-setup-but-integrate-dotbare) of `dotbare` to my current system and the [complete migration](https://github.com/kazhala/dotbare#complete-migration). 

For a while, I'm going to use my function to revert the symlinks before the full integration of `dotbare` to my system. 

Many thanks for your time. I'm closing this issue.
