### ISSUE TITLE
[question/feature req.] separate tracking of two working dirs

### ISSUE THREAD

**Issue by bappobox** [kazhala/dotbare#20]
Hello @kazhala  

first let me thank you for this project...not being a true IT person, having a visual context in the cli when dealing with dotfiles is quite invaluable for me!

My question relates to the possibility of using dotbare to track (separately) two dot repositories with two different working dirs, specifically the $HOME for the majority of config files, and /etc for those few files involving system customization (eg. confs within sysctl.d/ or udev rules).

Without taking into consideration the file ownership drawbacks when handling dirs outside $HOME (I am aware of such problems, but my scope would be limited to a local tracking and manual cloning), the issue is ultimately how to use dotbare scripts to track two git bare repositories pointing to two different working trees.

Thanks again for your great contribution!

**Comment by kazhala** [comment]
Hi @bappobox, glad you found it useful!

Regarding the possibility to track multiple bare repositories, it is very capable because `dotbare` is basically like a client consuming information from it. Like you mentioned regarding ownership or any other issues, I can't answer or give any suggestions to track files under `/etc` but below would be the example to track multiple bare repositories.

Since `dotbare` uses the ENV variable to determine the working tree and the `.git` location, you could simply create an alias for each bare repository. Let's say you want one to track the home directory, and another one to track maybe just `~/.config` as an arbitrary example.

```sh
# points to "$HOME/.cfghome" and work in $HOME
alias dothome='DOTBARE_DIR="$HOME/.cfghome" DOTBARE_TREE="$HOME" DOTBARE_BACKUP="$HOME/.local/share/dotbare/home" dotbare'

# points to "$HOME/.cfgconfig" and work in $HOME/.config
alias dotconfig='DOTBARE_DIR="$HOME/.cfgconfig" DOTBARE_TREE="$HOME/.config" DOTBARE_BACKUP="$HOME/.local/share/dotbare/config" dotbare'
```

Then you could run `dothome` or `dotconfig` depending on which bare repo you want to operate on. I hope this solves your problem.

**Comment by bappobox** [comment]
Thanks a lot for your prompt answer, @kazhala 
just tried your solution and it works as a charm...very helpful and again great project!
